#!/bin/bash

# 還有不少要改進，例如改參數化傳入

RESULT=`curl -u 'admin:yourpassword' -H 'Accept: application/json' -X GET "https://yourgraylogip:yourgraylogport/api/system/indexer/failures/count?since=$(date -u +'%FT%T.%2NZ' -d " -5 minute")&pretty=true" -k | grep count | awk -F":" '{print $2}'`

#echo $RESULT


if [ $RESULT -eq 1 ]; then
    echo "CRITICAL: Index failure occurred ($RESULT records)|$RESULT"
    exit $STATE_CRITICAL
fi

if [ $RESULT -eq 0 ]; then
    echo "OK: No index failure.|$RESULT"
    exit $STATE_OK
fi

echo "Unknown state : $RESULT"
exit $STATE_UNKNOWN
